# Task01：数组（1天）
**理论部分**<br>

理解数组的存储与分类。<br>
实现动态数组，该数组能够根据需要修改数组的长度。<br>

**练习部分**

## 1.利用动态数组解决数据存放问题

   编写一段代码，要求输入一个整数N，用动态数组A来存放2~N之间所有5或7的倍数，输出该数组。

In [43]:
import numpy as np
def multiple_5_7(N):
    A = []
    for i in range(2,N+1):
        if i%5 == 0 or i%7 == 0:
            A.append(i)
    return A 

In [44]:
# test:
print(multiple_5_7(40))

[5, 7, 10, 14, 15, 20, 21, 25, 28, 30, 35, 40]


## 2. 托普利茨矩阵问题<br>
   如果一个矩阵的每一方向由左上到右下的对角线上具有相同元素，那么这个矩阵是托普利茨矩阵。<br>
   给定一个M x N的矩阵，当且仅当它是托普利茨矩阵时返回True。

In [20]:
t = np.arange(12).reshape(4,3)
print(t)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [16]:
a.shape 

(4, 3)

In [24]:
t[0]


array([0, 1, 2])

In [17]:
a[2,1]

7

In [25]:
def toeplitz(a):
    M = a.shape[0]
    N = a.shape[1]
    for i in range(M):
        for j in range(N):
            if a[i,j] == a[i+1,j+1]:
                return True 
            else:
                return False 

In [42]:
# test
t1 = np.arange(12).reshape(4,3)
print(toeplitz(t1))

t2 = np.array([[1,2,3,4],[5,1,2,3],[9,5,1,2]])
print(toeplitz(t2))

False
True


## 3. 三数之和

    https://leetcode-cn.com/problems/3sum/

    给定一个包含 n 个整数的数组nums，判断nums中是否存在三个元素a，b，c，使得a + b + c = 0？找出所有满足条件且不重复的三元组。<br>
    注意：答案中不可以包含重复的三元组。

In [258]:
def sum0_3nums(nums):
    a = []
    l = len(nums) 
    m = 0
    while m <= 3:
        m+=1
    
        for i in range(l):
            for j in range(l):
                for k in range(l):
                    i != j !=k
                    if nums[i]+nums[j]+nums[k] == 0:
                        nums_sum0 = [nums[i], nums[j], nums[k]]
                        a.append(nums_sum0)
                        for ele in sorted([i,j,k], reverse = True):  
                            del nums[ele] 
        return a
          
                
                
#                 else:
#                     return 'no any three values satisfying the condition'
            
#     return nums

In [259]:
nums = [-1, 0, 1, 2, -1, -4]
sum0_3nums(nums)

IndexError: list index out of range

In [251]:
# Leetcode上的解答
def threeSum(nums):

    n=len(nums)
    res=[]
    if(not nums or n<3):
        return []
    nums.sort()
    res=[]
    for i in range(n):
        if(nums[i]>0):
            return res
        if(i>0 and nums[i]==nums[i-1]):
            continue
        L=i+1
        R=n-1
        while(L<R):
            if(nums[i]+nums[L]+nums[R]==0):
                res.append([nums[i],nums[L],nums[R]])
                while(L<R and nums[L]==nums[L+1]):
                    L=L+1
                while(L<R and nums[R]==nums[R-1]):
                    R=R-1
                L=L+1
                R=R-1
            elif(nums[i]+nums[L]+nums[R]>0):
                R=R-1
            else:
                L=L+1
    return res

# 作者：zhu_shi_fu
# 链接：https://leetcode-cn.com/problems/3sum/solution/pai-xu-shuang-zhi-zhen-zhu-xing-jie-shi-python3-by/
# 来源：力扣（LeetCode）
# 著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

In [260]:
nums = [-1, 0, 1, 2, -1, -4]
threeSum(nums)

[[-1, -1, 2], [-1, 0, 1]]